name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: test
        run: npm run test


  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: e2e test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3000/users

  deploy:
    needs:
      - test
      - e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: simulate Deploy
        if: ${{ github.event_name == 'push'}}
        run: echo "deployment simulate"
